#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "----- Running linting on client code -----"
npm run --prefix ./client/ lint
echo "----- Running tests and linting on server code -----"
npm run --prefix ./server/ test
